services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: archinfra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

    restart: unless-stopped

  # app:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - "8000:8000"

    

volumes:
  postgres_data:
