-- seeds_documents_large.sql

INSERT INTO document (project, content, source, created_at) VALUES
('IdeaHub', 'Plataforma para compartir y votar ideas de proyectos entre desarrolladores.', 'notion', NOW()),
('IdeaHub', 'MVP inicial con FastAPI + React para publicar ideas y comentarios.', 'local', NOW()),
('Fitness_AI', 'App que analiza rutinas de entrenamiento y propone mejoras con IA.', 'figma', NOW()),
('Fitness_AI', 'Objetivo: integrar planificador de comidas y progresión semanal.', 'notion', NOW()),
('MusicGen', 'Generador de beats para productores, enfocado en reggaetón y trap.', 'colab', NOW()),
('MusicGen', 'MVP con modelo preentrenado de generación de loops musicales.', 'google_docs', NOW()),
('AgenciaIA', 'Agencia de inteligencia artificial para automatización de procesos.', 'docs', NOW()),
('AgenciaIA', 'Meta: ofrecer SaaS con modelos propios y APIs externas.', 'notion', NOW()),
('SmartTasks', 'Gestor de tareas que usa IA para priorizar automáticamente.', 'trello', NOW()),
('SmartTasks', 'Primera meta: sugerir prioridades en base a deadlines.', 'local', NOW()),
('ErasmusConnect', 'Web que conecta estudiantes Erasmus con empresas de prácticas.', 'university_portal', NOW()),
('ErasmusConnect', 'MVP: formulario de registro + sistema de matching básico.', 'notion', NOW()),
('MarketAnalyzer', 'Plataforma que analiza anuncios de segunda mano y detecta estafas.', 'pdf', NOW()),
('MarketAnalyzer', 'Objetivo: usar embeddings para comparar precios y detectar fraudes.', 'colab', NOW()),
('RAGChat', 'Chat con RAG especializado en arquitectura de software.', 'github', NOW()),
('RAGChat', 'MVP: indexar repos locales con FAISS y responder en lenguaje natural.', 'local', NOW()),
('FocusApp', 'Aplicación que monitoriza hábitos digitales para mejorar productividad.', 'figma', NOW()),
('FocusApp', 'Meta: integrar un dashboard con métricas de uso diario.', 'notion', NOW()),
('LangTutor', 'Tutor de idiomas con IA, capaz de generar diálogos interactivos.', 'google_docs', NOW()),
('LangTutor', 'Primer MVP: practicar inglés nivel B1 con escenarios reales.', 'notion', NOW()),
('HealthTrack', 'App de salud que mide pasos, sueño y alimentación.', 'trello', NOW()),
('HealthTrack', 'MVP: integrar API de Google Fit para pasos y calorías.', 'notion', NOW()),
('EcoRoute', 'Aplicación que sugiere rutas en transporte sostenible.', 'figma', NOW()),
('EcoRoute', 'Objetivo: calcular huella de carbono por trayecto.', 'docs', NOW()),
('BookMate', 'Red social para lectores con recomendaciones basadas en IA.', 'notion', NOW()),
('BookMate', 'MVP: perfil de usuario + lista de libros favoritos.', 'local', NOW()),
('DevMentor', 'Plataforma de mentorías para programadores junior.', 'trello', NOW()),
('DevMentor', 'Meta: matching basado en stack tecnológico y experiencia.', 'notion', NOW()),
('GameInsight', 'Herramienta de análisis para gamers con métricas de rendimiento.', 'colab', NOW()),
('GameInsight', 'MVP: integración con cuentas de Steam y Riot Games.', 'google_docs', NOW()),
('CookAI', 'Asistente de cocina que sugiere recetas con ingredientes disponibles.', 'notion', NOW()),
('CookAI', 'MVP: buscador con NLP para recetas rápidas y saludables.', 'figma', NOW()),
('TravelMatch', 'App para encontrar compañeros de viaje con intereses comunes.', 'docs', NOW()),
('TravelMatch', 'Meta: integrar mapas y chat en tiempo real.', 'local', NOW()),
('StartUpLab', 'Plataforma para validar ideas de negocio con encuestas rápidas.', 'google_docs', NOW()),
('StartUpLab', 'MVP: sistema de votación + analítica básica.', 'trello', NOW()),
('StudyBoost', 'App que usa IA para generar exámenes de práctica personalizados.', 'notion', NOW()),
('StudyBoost', 'Objetivo: adaptar la dificultad según rendimiento del alumno.', 'local', NOW()),
('JobRadar', 'Buscador de empleo con IA que sugiere ofertas personalizadas.', 'figma', NOW()),
('JobRadar', 'MVP: scraper de portales de empleo + motor de recomendaciones.', 'docs', NOW()),
('CryptoSafe', 'Wallet segura con detección de transacciones sospechosas.', 'colab', NOW()),
('CryptoSafe', 'Meta: implementar autenticación multifactor biométrica.', 'notion', NOW()),
('GreenWallet', 'App para medir impacto ecológico de tus compras.', 'docs', NOW()),
('GreenWallet', 'MVP: categorización automática de gastos en sostenibilidad.', 'trello', NOW()),
('EduConnect', 'Red de profesores y alumnos para compartir recursos.', 'google_docs', NOW()),
('EduConnect', 'Objetivo: implementar videollamadas en la plataforma.', 'notion', NOW()),
('DesignAI', 'Asistente que genera logotipos con IA a partir de texto.', 'figma', NOW()),
('DesignAI', 'MVP: generador simple de logos con variaciones de color.', 'local', NOW()),
('MindSpace', 'App de meditación con música generada por IA.', 'colab', NOW()),
('MindSpace', 'Meta: personalizar sesiones según nivel de estrés.', 'docs', NOW()),
('TaskFlow', 'Herramienta de gestión de proyectos ligera para equipos pequeños.', 'notion', NOW()),
('TaskFlow', 'MVP: tablero Kanban + chat integrado.', 'trello', NOW()),
('FarmConnect', 'Marketplace entre agricultores y consumidores locales.', 'pdf', NOW()),
('FarmConnect', 'Objetivo: sistema de logística colaborativa.', 'local', NOW()),
('SkillSwap', 'App para intercambiar habilidades entre usuarios.', 'docs', NOW()),
('SkillSwap', 'MVP: registro de perfiles y sistema de trueque.', 'notion', NOW()),
('EventPulse', 'Plataforma para descubrir eventos en tu ciudad.', 'google_docs', NOW()),
('EventPulse', 'Meta: integrar recomendador basado en gustos.', 'figma', NOW()),
('FoodSaver', 'App para reducir desperdicio conectando supermercados y ONGs.', 'trello', NOW()),
('FoodSaver', 'MVP: inventario en tiempo real de productos sobrantes.', 'docs', NOW()),
('PetCare', 'App para seguimiento de mascotas con recordatorios médicos.', 'notion', NOW()),
('PetCare', 'Meta: conectar veterinarios directamente con usuarios.', 'google_docs', NOW()),
('FilmFinder', 'Buscador de películas con recomendaciones inteligentes.', 'local', NOW()),
('FilmFinder', 'MVP: integración con TMDB API y recomendaciones.', 'figma', NOW()),
('BuildAI', 'Generador automático de arquitectura para proyectos software.', 'notion', NOW()),
('BuildAI', 'MVP: elegir stack (FastAPI, React, PostgreSQL) y generar boilerplate.', 'github', NOW()),
('EcoHome', 'Plataforma para monitorizar consumo energético en casas.', 'docs', NOW()),
('EcoHome', 'Objetivo: integrar IoT con sensores domésticos.', 'colab', NOW()),
('LifeGoals', 'App para definir y seguir metas personales.', 'trello', NOW()),
('LifeGoals', 'MVP: lista de objetivos + progreso porcentual.', 'notion', NOW()),
('StudyCircle', 'Comunidades de estudio online con salas temáticas.', 'docs', NOW()),
('StudyCircle', 'Meta: añadir gamificación con insignias.', 'local', NOW()),
('NewsDigest', 'App que resume noticias diarias con IA.', 'google_docs', NOW()),
('NewsDigest', 'MVP: scraping de medios + modelo de resumen.', 'colab', NOW()),
('InnovaJobs', 'Plataforma de proyectos freelance innovadores.', 'trello', NOW()),
('InnovaJobs', 'Meta: sistema de matching avanzado según skills.', 'notion', NOW()),
('FitSocial', 'Red social de fitness con retos y logros compartidos.', 'figma', NOW()),
('FitSocial', 'MVP: feed con entrenamientos y sistema de likes.', 'docs', NOW()),
('SkillTrack', 'App para medir progreso en nuevas habilidades.', 'notion', NOW()),
('SkillTrack', 'Meta: recordatorios automáticos y métricas de avance.', 'local', NOW()),
('GardenAI', 'Asistente de jardinería que detecta plagas en plantas.', 'colab', NOW()),
('GardenAI', 'MVP: subir foto de planta y devolver diagnóstico.', 'figma', NOW()),
('SmartFinance', 'App para control financiero con predicción de gastos.', 'notion', NOW()),
('SmartFinance', 'Objetivo: integrar gráficos interactivos y alertas.', 'trello', NOW()),
('TutorMate', 'Plataforma de tutorías online por videollamada.', 'docs', NOW()),
('TutorMate', 'MVP: sistema de reservas y pagos integrados.', 'google_docs', NOW()),
('CityScanner', 'App que recopila datos abiertos para analizar ciudades.', 'local', NOW()),
('CityScanner', 'Meta: crear dashboards de movilidad y contaminación.', 'notion', NOW()),
('MindMapPro', 'Herramienta de mapas mentales colaborativos.', 'trello', NOW()),
('MindMapPro', 'MVP: edición en tiempo real y exportación a PDF.', 'figma', NOW()),
('Craftify', 'Marketplace para artesanos locales con IA de recomendación.', 'notion', NOW()),
('Craftify', 'MVP: catálogo de productos + carrito básico.', 'docs', NOW()),
('StoryGen', 'Generador de historias personalizadas con IA.', 'colab', NOW()),
('StoryGen', 'Meta: exportar historias como audiolibro.', 'local', NOW()),
('LearnLoop', 'Plataforma de cursos que adapta contenidos al alumno.', 'google_docs', NOW()),
('LearnLoop', 'MVP: sistema de quizzes adaptativos.', 'notion', NOW()),
('DailyFocus', 'App minimalista para organizar tu día en bloques de tiempo.', 'figma', NOW()),
('DailyFocus', 'Meta: añadir integración con Google Calendar.', 'trello', NOW()),
('PitchDeckAI', 'Generador de presentaciones de startups con IA.', 'docs', NOW()),
('PitchDeckAI', 'MVP: input de texto → slides con diseño básico.', 'local', NOW());
