"""project-relationship

Revision ID: 38d0ba59022e
Revises: e1f318fcd6bc
Create Date: 2025-09-25 23:26:53.571588

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
from sqlmodel import Column, Integer, DateTime, ForeignKeyConstraint, PrimaryKeyConstraint

# revision identifiers, used by Alembic.
revision: str = '38d0ba59022e'
down_revision: Union[str, Sequence[str], None] = 'e1f318fcd6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    Column('id', Integer(), nullable=False),
    Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    Column('created_at', DateTime(), nullable=False),
    Column('updated_at', DateTime(), nullable=False),
    Column('architecture_id', Integer(), nullable=True),
    ForeignKeyConstraint(['architecture_id'], ['architecture.id'], ),
    PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('project_database_link',
    Column('project_id', Integer(), nullable=False),
    Column('database_id', Integer(), nullable=False),
    ForeignKeyConstraint(['database_id'], ['database.id'], ),
    ForeignKeyConstraint(['project_id'], ['project.id'], ),
    PrimaryKeyConstraint('project_id', 'database_id')
    )
    op.create_table('project_tag_link',
    Column('project_id', Integer(), nullable=False),
    Column('tag_id', Integer(), nullable=False),
    ForeignKeyConstraint(['project_id'], ['project.id'], ),
    ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    PrimaryKeyConstraint('project_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tag_link')
    op.drop_table('project_database_link')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
